/*
Copyright © 2021 K.Awata

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

const initconf = `# pjma config file
apps:
  e3d31: C:\Program Files (x86)\AVEVA\Everything3D3.1\launch.bat
  adm19: C:\Program Files (x86)\AVEVA\Administration1.9\admin.bat
  pjcre: C:\Program Files (x86)\AVEVA\Administration1.9\projectcreation.bat
context:
  module: ""
  tty: false
  project: ""
  user: ""
  mdb: ""
  macro: ""
projects_dir: .\projects
extrapj:
  - C:\Users\Public\Documents\AVEVA\Projects\E3D3.1\AvevaCatalogue
  - C:\Users\Public\Documents\AVEVA\Projects\E3D3.1\AvevaMarineSample
  - C:\Users\Public\Documents\AVEVA\Projects\E3D3.1\AvevaPlantSample
caf_uic_path:
  - .\cafuic
pmllib:
  - .\pmllib
pmlui:
  - .\pmlui
extracmd:
  - echo custom_evars.bat generated by pjma
scripts:
  setup: cmd /c "mkdir projects cafuic pmllib pmlui"
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a projects directory",
	Long:  "Initialize a projects directory",
	Args:  cobra.ExactArgs(0),
	Run: func(cmd *cobra.Command, args []string) {
		pwd, err := os.Getwd()
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			return
		}
		if pwd == filepath.Dir(viper.ConfigFileUsed()) {
			fmt.Fprintln(os.Stderr, "config file already exists")
			return
		}
		conf, err := os.Create(defaultconf)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			return
		}
		defer conf.Close()
		if _, err := conf.WriteString(initconf); err != nil {
			fmt.Fprintln(os.Stderr, err)
			return
		}
		fmt.Println(defaultconf + " has been created")
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}
