/*
Copyright © 2021 K.Awata <awata_kihachi@outlook.jp>

*/
package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

const initconf = `# pjma config file
apps:
  e3d31: C:\Program Files (x86)\AVEVA\Everything3D3.1\launch.bat
  adm19: C:\Program Files (x86)\AVEVA\Administration1.9\admin.bat
  pjcre: C:\Program Files (x86)\AVEVA\Administration1.9\projectcreation.bat
context:
  module: ""
  tty: false
  project: ""
  user: ""
  mdb: ""
  macro: ""
projects_dir: .\projects
caf_uic_path:
- .\cafuic
pmllib:
- .\pmllib
pmlui:
- .\pmlui
extrapj:
- C:\Users\Public\Documents\AVEVA\Projects\E3D3.1\AvevaCatalogue
- C:\Users\Public\Documents\AVEVA\Projects\E3D3.1\AvevaMarineSample
- C:\Users\Public\Documents\AVEVA\Projects\E3D3.1\AvevaPlantSample
extracmd:
- echo custom_evars.bat generated by pjma
scripts:
  setup: cmd /c mkdir projects cafuic pmllib pmlui
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a projects directory",
	Long:  "Initialize a projects directory",
	Args:  cobra.ExactArgs(0),
	Run: func(cmd *cobra.Command, args []string) {
		pwd, err := os.Getwd()
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			return
		}
		if pwd == filepath.Dir(viper.ConfigFileUsed()) {
			fmt.Fprintln(os.Stderr, "config file already exists")
			return
		}
		conf, err := os.Create(`pjmaconf.yaml`)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			return
		}
		defer conf.Close()
		if _, err := conf.WriteString(initconf); err != nil {
			fmt.Fprintln(os.Stderr, err)
			return
		}
		fmt.Println("./pjmaconf.yaml has been created")
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}
